### ISSUE TITLE
Add support for OccupancyStatus

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-gtfs-realtime-api#4]
`OccupancyStatus` is now an "experimental/proposed" GTFS-realtime field, [as discussed on the gtfs-realtime list](https://groups.google.com/d/msg/gtfs-realtime/_HtNTGp5LxM/0mvvEW1WuMMJ).

@bdferris How do you want to handle this in context of this library?  We're using this library in [our feed](https://github.com/CUTR-at-USF/bullrunner-gtfs-realtime-generator) (indirectly, via the [onebusaway-gtfs-realtime-exporter](https://github.com/OneBusAway/onebusaway-gtfs-realtime-exporter)), so presumably we'd want to add the field here and publish a new version.  But is this library only for "official", accepted changes to GTFS-rt?

**Comment by barbeau** [comment]
Reopening this due to further discussion on gtfs-realtime group about how the occupancy field will be added to the GTFs-rt spec, starting here:
https://groups.google.com/d/msg/gtfs-realtime/_HtNTGp5LxM/86U3GGxDbngJ

Current consensus seems to be moving `OccupancyStatus` out of the `VehicleDescriptor` and into `VehiclePosition`.

**Comment by bdferris** [comment]
Sean, sorry for not responding to this sooner.  Are you currently using the existing field in a production system?  Do you need a version of the the library that supports both versions of the field for a period of time?

**Comment by barbeau** [comment]
No worries!  I'm fine switching straight to VehiclePosition.  We aren't using this in production yet.  Its been on my TODO list to make the change but have It gotten to it yet.

**Comment by bdferris** [comment]
Ok, my current thought is to actually switch out the base part of the library to use the new gtfs-realtime-bindings module.  This module would continue to exist in order to support existing extensions.

**Comment by barbeau** [comment]
Yeah, that makes sense to me.

**Comment by bdferris** [comment]
Ok, I've just cut onebusaway-gtfs-realtime-api-1.2.0.  It builds against gtfs-realtime-bindings-0.0.3 which includes the Jan 30, 2015 GTFS-realtime release, which includes OccupancyStatus in VehiclePosition.

**Comment by barbeau** [comment]
Thanks @bdferris!
