### ISSUE TITLE
GTFS Realtime Alerts Feed Publishes Incorrect Start/End Periods

### ISSUE THREAD

**Issue by devinbraun** [OneBusAway/onebusaway-gtfs-realtime-api#6]
[http://realtime.sdmts.com/api/api/gtfs_realtime/alerts-for-agency/MTS.pbtext?key=org.onebusaway.iphone
](url)

When viewing the GTFS-realtime feed alerts output at the link above, the active_period start and end time are incorrect.  They are off by a multiple of 1000.

When viewing the alerts in the OBA console, the start and end times are correct.  It appears that it might be only an issue in the output of the API endpoint?

**Comment by barbeau** [comment]
@devinbraun Thanks for the report!  Yes, I'm assuming this is a time conversion bug in the GTFS-rt output API.  GTFS-rt times are seconds past epoch vs. milliseconds past epoch.

**Comment by barbeau** [comment]
Actually, I believe this is the wrong project for this bug report - it should be filed on https://github.com/OneBusAway/onebusaway-application-modules.  I'll move it there.

**Comment by barbeau** [comment]
Moved to https://github.com/OneBusAway/onebusaway-application-modules/issues/196.
